### ISSUE TITLE
does lazyflymake supports flymake-xxx ?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/lazyflymake#3]
i see some `lazyflymake-elisp`, `lazyflymake-eslint` ... in this repo. so if only those languages are supported by lazyflymake? or all flymake-supported-language are supported ? like `flymake-php` ? (since flymake still enabled?)

**Comment by smallst** [comment]
after checking your emacs.d i found you already remove the `init-flymake.el`. and in my fork i don't have `init-flymake` either but i can add `(require 'flymake-php)` and it works normally. is it means lazyflymake can handle that?

**Comment by redguardtoo** [comment]
Here is some code from `lazyflymake-start`,
![image](https://user-images.githubusercontent.com/184553/112316744-80c6e680-8cff-11eb-9619-787c4e9cb213.png)

`lazyflymake-flymake-mode-on` is nil by default. So right now, lazyflymake uses `flymake-mode`.

Only on my computer `lazyflymake-flymake-mode-on` is `t`. So you only need set up flymake as usual.

**Comment by smallst** [comment]
so, if `lazyflymake-flymake-mode-on` is t and `flymake-mode` is not on, all `flaymake-xxx` pacakges won't work, right?

**Comment by redguardtoo** [comment]
Not sure. `lazyflymake-flymake-mode-on` is sort of "development mode" flag used by me only.

I plan to drop support `flymake-mode` in the future though some flymake api is still used.

The goal of lazyflymake is to get better runtime performance,
